spring:
  application:
    name: eligibility
  cache:
    type: hazelcast

hazelcast:
  config: classpath:hazelcast-local.yaml

logging:
  level:
    root: INFO
    com.example.eligibility: DEBUG
    org.springframework.cache: DEBUG
    com.hazelcast: DEBUG
