apiVersion: apps/v1
kind: Deployment
metadata:
  name: eligibility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eligibility
  template:
    metadata:
      labels:
        app: eligibility
    spec:
      containers:
        - name: eligibility
          image: ghcr.io/akhilsplendid/eligibility:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8083
            - name: hazelcast
              containerPort: 5701
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: eligibility
spec:
  selector:
    app: eligibility
  ports:
    - name: http
      port: 80
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: eligibility-hazelcast
spec:
  clusterIP: None
  selector:
    app: eligibility
  ports:
    - name: hazelcast
      port: 5701
      targetPort: 5701
