image:
  repository: ghcr.io/akhilsplendid/eligibility
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 8083
replicaCount: 1
monitoring:
  enabled: true
  interval: 30s
hazelcast:
  enabled: true
  port: 5701
