apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eligibility.fullname" . }}
  labels:
    app: {{ include "eligibility.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "eligibility.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "eligibility.name" . }}
    spec:
      containers:
        - name: eligibility
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
            - name: hazelcast
              containerPort: 5701
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eligibility.fullname" . }}
spec:
  selector:
    app: {{ include "eligibility.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
