{{- if .Values.hazelcast.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: eligibility-hazelcast
  labels:
    app: {{ include "eligibility.name" . }}
    component: hazelcast
spec:
  clusterIP: None
  selector:
    app: {{ include "eligibility.name" . }}
  ports:
    - name: hazelcast
      port: {{ .Values.hazelcast.port }}
      targetPort: 5701
      protocol: TCP
{{- end }}
